kind: pipeline
name: CI/CD

steps:
- name: composer-install
  image: composer
  commands:
  - composer install

- name: phpunit-test
  image: php:8
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml
  depends_on:
  - composer-install

- name: phpstan-analyse
  image: php:8
  commands:
  - vendor/bin/phpstan analyse src --error-format=json --no-progress > phpstan-results.json
  - cat phpstan-results.json
  depends_on:
  - composer-install

- name: discord-phpunit-failure
  image: plugins/webhook
  settings:
    urls:
      from_secret: discord_webhook_url
    content_type: application/json
    template: |
      {
        "content": "",
        "embeds": [
          {
            "title": "❌ **PHPUnit Tests Failed**",
            "description": "PHPUnit tests failed for branch '{{build.branch}}'",
            "color": 15158332,
            "fields": [
              {
                "name": "Build",
                "value": "#{{build.number}} - {{repo.name}}",
                "inline": true
              },
              {
                "name": "Branch",
                "value": "{{build.branch}}",
                "inline": true
              },
              {
                "name": "Commit",
                "value": "{{build.commit}}"
              },
              {
                "name": "Failed Step",
                "value": "PHPUnit Tests"
              },
              {
                "name": "Author",
                "value": "{{build.author}}",
                "inline": true
              }
            ],
            "footer": {
              "text": "Check the build logs for details"
            }
          }
        ]
      }
  when:
    status: [failure]
  depends_on:
  - phpunit-test

- name: discord-phpstan-failure
  image: plugins/webhook
  settings:
    urls:
      from_secret: discord_webhook_url
    content_type: application/json
    template: |
      {
        "content": "❌ **PHPStan Analysis Failed**",
        "embeds": [
          {
            "title": "Build #{{build.number}} - {{repo.name}}",
            "description": "PHPStan static analysis failed for branch '{{build.branch}}'",
            "color": 15158332,
            "fields": [
              {
                "name": "Branch",
                "value": "{{build.branch}}",
                "inline": true
              },
              {
                "name": "Commit",
                "value": "{{build.commit}}",
                "inline": true
              },
              {
                "name": "Failed Step",
                "value": "PHPStan Analysis",
                "inline": true
              }
            ],
            "footer": {
              "text": "Check the build logs for details"
            }
          }
        ]
      }
  when:
    status: [failure]
  depends_on:
  - phpstan-analyse

- name: discord-success
  image: plugins/webhook
  settings:
    urls:
      from_secret: discord_webhook_url
    content_type: application/json
    template: |
      {
        "content": "✅ **Process successful**",
        "embeds": [
          {
            "title": "Build #{{build.number}} - {{repo.name}}",
            "description": "Process for branch '{{build.branch}}' was finished successfully",
            "color": 5763719,
            "fields": [
              {
                "name": "Tag",
                "value": "{{build.branch}}",
                "inline": true
              },
              {
                "name": "Commit",
                "value": "{{build.commit}}",
                "inline": true
              }
            ]
          }
        ]
      }
  when:
    status: [success]
  depends_on:
  - phpunit-test
  - phpstan-analyse
