kind: pipeline
name: CI/CD

steps:
- name: composer-install
  image: composer
  commands:
  - composer install

- name: phpunit-test
  image: php:8
  commands:
  - vendor/bin/phpunit --configuration config.xml

- name: phpstan-analyse
  image: php:8
  commands:
  - vendor/bin/phpstan analyse --error-format=json --no-progress > phpstan-results.json
