kind: pipeline
name: CI/CD

steps:
- name: composer-install
  image: composer
  commands:
  - composer install

- name: phpunit-test
  image: php:8
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml

- name: phpstan-analyse
  image: php:8
  commands:
  - vendor/bin/phpstan analyse src --error-format=json --no-progress > phpstan-results.json
  - cat phpstan-results.json


- name: discord-simple-test
  image: plugins/webhook
  settings:
    urls:
      from_secret: discord_webhook_url
    content_type: application/json
    template: |
      {
        "content": "Simple test message"
      }

- name: discord-debug
  image: plugins/webhook
  settings:
    urls:
      from_secret: discord_webhook_url
    content_type: application/json
    debug: true
    template: |
      {
        "content": "DEBUG: Build {{build.number}} - {{repo.name}} - Branch: {{build.branch}}"
      }
  when:
    status: [success]


- name: discord-success
  image: plugins/webhook
  settings:
    urls:
      from_secret: discord_webhook_url
    content_type: application/json
    template: |
      {
        "content": "✅ **Process successful**",
        "embeds": [
          {
            "title": "Build #{{build.number}} - {{repo.name}}",
            "description": "Process for branch '{{build.branch}}' was finished successfully",
            "color": 5763719,
            "fields": [
              {
                "name": "Tag",
                "value": "{{build.branch}}",
                "inline": true
              },
              {
                "name": "Docker Image",
                "value": "your-username/your-app-name:{{build.branch}}",
                "inline": true
              },
              {
                "name": "Commit",
                "value": "[{{build.commit}}]({{build.link}})",
                "inline": true
              }
            ],
            "timestamp": "{{build.created}}"
          }
        ]
      }
  when:
    status: [success]
