kind: pipeline
name: CI/CD

steps:
- name: composer-install
  image: composer
  commands:
  - composer install

- name: phpunit-test
  image: php:8
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml

- name: phpstan-analyse
  image: php:8
  depends_on:
    - phpunit-test
  commands:
  - vendor/bin/phpstan analyse src --error-format=json --no-progress > phpstan-results.json
  when:
    status: [success]
    event: [push, pull_request, tag]
