name: deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Run Testing
        id: testing
        run: echo "Testing action"

  deploy:
    needs: PHPUnit
    runs-on: ubuntu-latest

    if: ${{ needs.testing.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make HTTP request
        run: |
          BRANCH_NAME=${{ github.ref }}
          curl -X GET "https://deploy.meine-wiese.de/?branch=$BRANCH_NAME"
